### ISSUE TITLE
PIP authorization

### ISSUE THREAD

**Issue by artursmolarek** [stevearc/pypicloud#101]
Is there any way to configure PIP with packages which are available only for logged users?
I was trying to use basic auth in my pip.conf, but with no success. I'm using default sql backend.

**Comment by stevearc** [comment]
The two ways to pass basic auth using pip are directly on the command line:
```
pip install -i http://<username>:<password>@localhost:6543/pypi/ PACKAGE
```
Or by adding the pypicloud index to your `$HOME/.pip/pip.conf`:
```
[global]
index-url = http://<username>:<password>@localhost:6543/pypi/
```
and then just doing a `pip install PACKAGE`. If you attempt to install a package without providing auth, it should prompt you for a user and password. If you've tried all of these and none of them are working for you, paste me your config file (minus any sensitive information) and tell me exactly what happens when you attempt to install the protected package.

**Comment by artursmolarek** [comment]
But the problem is that Pypicloud doesn't ask me about authorization.
Please look at the simple curl request (I'm using dockerized version):

```
curl http://localhost:8080/pypi/
<!DOCTYPE html>
<html>
<head>
  <title>Simple Index</title>
</head>
<body>
  
</body>
```

Or:

```
curl http://admin:password@localhost:8080/pypi/
<!DOCTYPE html>
<html>
<head>
  <title>Simple Index</title>
</head>
<body>
  
</body>
```

This is 200 response with empty list.

**Comment by artursmolarek** [comment]
Ok, looks that it doesn't matter for installing. That works.
But what about pip search?

**Comment by stevearc** [comment]
Ah, there are a couple of things that are not supported by pypicloud. `pip search` is one of them.

**Comment by artursmolarek** [comment]
Ok, thanks for the answer. In that case this issue can be closed.
