### ISSUE TITLE
Package list should rebuild automatically

### ISSUE THREAD

**Issue by Ziomalon** [stevearc/pypicloud#108]
I've created an HA setup for pypicloud using HA proxy with deployment in 3 separate regions. I use the s3 backend to have them in sync. The problem is that when I upload a package i have no guarantee that all nodes with provide it. 

Would it be possible to introduce automatic package list rebuilding after interval given in configuration?

**Comment by niothiel** [comment]
I believe the correct way of serving up pypicloud in an HA environment is to reconfigure your caching backend to be common across all of the nodes instead of rebuilding the cache periodically. Specifically, you should be able to setup ElastiCache, DynamoDB, or RDS for doing the package data caching. That way whenever one node updates a package cache, all others are able to read it.

**Comment by stevearc** [comment]
@niothiel is correct. The caching layer is there for sharing the state among all PyPIcloud webservers.

That said, if you absolutely have to you can trigger the rebuild programmatically using the [HTTP endpoints](http://pypicloud.readthedocs.io/en/latest/topics/api.html#get-admin-rebuild). I wouldn't recommend this, but it's available.

**Comment by Ziomalon** [comment]
Thank you very much for your replies. To be honest I did not think about that. I will introduce a caching layer in my setup. Thank you.
