### ISSUE TITLE
Pip Caching support

### ISSUE THREAD

**Issue by niothiel** [stevearc/pypicloud#110]
To my knowledge, there is currently no good way to make pypicloud compatible with the way pip caches downloaded packages. With my current settings, any time I do a pip install against our pypicloud instance, it will ALWAYS download and cache the package. The next time that package is requested, even though it's in the local pip cache, it misses the cache.

This causes a problem for our CICD servers because we perform fresh installs each time we do a build. As a result, we end up with the same python packages cached on disk that will never be read again because the s3 signing url changed.

The reasons are as follows:

* pypicloud generates signed s3 urls on each request. This breaks the url-based hashing mechanism that pip uses for caching. [pip ref](https://github.com/pypa/pip/blob/8df742e56db99c48f7ad85085501fe23456b419c/pip/_vendor/cachecontrol/caches/file_cache.py#L78), [pypicloud ref](https://github.com/stevearc/pypicloud/blob/master/pypicloud/storage/s3.py#L163)
* Neither pypicloud nor s3 return `Cache-Control` headers to the client when serving up the package. I haven't dug into the details, but I believe pip requires this in order for a package to be successfully cached.

Having said this, I think there are a few options to consider:

* Instead of invoking `generate_url` each time, they can be cached within the `data` column entry with a corresponding TTL matching the `storage.expire_after` value. This would also mostly fix the problem described [here](http://pypicloud.readthedocs.io/en/latest/topics/redirect_urls.html#redirect-detail). With this change, the `storage.expire_after` value can be bumped significantly (PyPi uses 365 days).
* Alternatively, another configuration option can be introduced to shuttle the data via the pypicloud instance directly to preserve the URL (and the caching mechanism) instead of handing the client a 302 with the s3 url. This approach has some disadvantages, specifically in the available bandwidth department.
* File an issue with Pip to change the caching mechanism to either strip query strings before hashing, or doing package & version caching instead of url-based. (This doesn't seem likely to happen)

Finally, I believe PyPiCloud should set the `Cache-Control` header in some form or fashion when returning the package url. I can see pypicloud returning it as part of the 302, or having it be set on the s3 object the first time it's uploaded.

@stevearc Sorry for writing a novel! What are your thoughts on the issue?

**Comment by stevearc** [comment]
S3 signatures are only valid for a maximum of 7 days. Less if the signing key expires before then (which I think it will in the case of role credentials). So even if we do cache the signed url, this will severely limit the benefit.

Fun fact: we originally did cache the signed url, but I eventually swapped that out for the current behavior because it introduced a lot of complexity, especially around role credentials.

I think that PyPICloud sending down cache headers when serving from the file storage backend is an easy win. We should definitely do that. And after that, it also seems pretty reasonable to add an option that does what you suggested and stream the S3 file through PyPICloud. Takes more bandwidth & CPU, but maybe is worth it if you're installing on the same clients repeatedly? And if it's behind an option I'm not worried about impacting existing deployments.

Another possible solution for you would be to run an instance of PyPICloud directly on your CICD servers using file storage, sqlite or other simple cache, and the following options:
```
pypi.fallback = cache
pypi.fallback_url = http://my-internal-pypicloud
pypi.always_show_upstream = true
```
The downside is that running it will be some additional load on your servers, and that it'll be slightly less efficient than just hitting the pip cache directly. Might be worth trying though.

**Comment by asgoel** [comment]
Hey @stevearc was there ever a feature implemented to allow streaming from S3 through pypicloud? Might be useful for our cases, both for our local developers and docker builds.

**Comment by asgoel** [comment]
@stevearc I opened a small PR here: https://github.com/stevearc/pypicloud/pull/202 that experiments with adding such support. Do you mind letting me know if this is on the right track? I can flesh it out with tests and docs then.

**Comment by thehesiod** [comment]
PR was merged, should this be closed?

**Comment by stevearc** [comment]
We can close it. If the solution is not sufficient the original author can re-open or create a new issue
