### ISSUE TITLE
Pip install request hitting Pypi cloud for public package

### ISSUE THREAD

**Issue by jpaulodit** [stevearc/pypicloud#111]
I have pypicloud 0.3.10 and I am installing from a requirements file. My issue is that on my pypicloud stderr, I can see all the public package requests hitting the server.

Example of my requirements file is like:

```
# public repos
user-agents==0.3.2
Werkzeug==0.10.4
wheel==0.24.0
xmltodict==0.9.2

# private packages go here
--extra-index-url https://<username>:<password>@mypypicloud.com/pypi

visitor-library==0.1.25
django-autoslug==1.8.0
```

Example of my stderr:

```
[pid: 20159|app: 0|req: 1926/5069] 23.235.46.44 () {62 vars in 1362 bytes} [Tue Feb  7 23:38:04 2017] GET /pypi/user-agents/ => generated 209 bytes in 690 msecs (HTTP/1.1 302) 3 headers in 136 bytes (1 switches on core 0)
[pid: 20159|app: 0|req: 1927/5070] 23.235.46.25 () {62 vars in 1362 bytes} [Tue Feb  7 23:38:05 2017] GET /pypi/wheel/ => generated 209 bytes in 688 msecs (HTTP/1.1 302) 3 headers in 136 bytes (1 switches on core 0)
[pid: 20159|app: 0|req: 1930/5073] 23.235.46.48 () {62 vars in 1359 bytes} [Tue Feb  7 23:38:09 2017] GET /pypi/xmltodict/ => generated 209 bytes in 691 msecs (HTTP/1.1 302) 3 headers in 136 bytes (1 switches on core 0)
```

I had assumed that the packages will be searched against the public pypi index first, and will not hit my private pypicloud for the public packages like wheel. Is the above behavior normal?

**Comment by stevearc** [comment]
This is more a question about pip than pypicloud, but I'll see if I can be of any help.

According to [the docs](https://pip.readthedocs.io/en/stable/reference/pip_install/#requirements-file-format) they say you can specify `--extra-index-url`, but make no mention of any ordering constraints. From that I would assume that it will apply to all requirements in the file, rather than just the ones listed below. You might try breaking it up into two files.

`requirements.txt`
```
# public repos
user-agents==0.3.2
Werkzeug==0.10.4
wheel==0.24.0
xmltodict==0.9.2

-r private_requirements.txt
```

`private_requirements.txt`
```
# my private packages
--extra-index-url https://<username>:<password>@mypypicloud.com/pypi

visitor-library==0.1.25
django-autoslug==1.8.0
```

Don't know if that will change the behavior, but it's worth trying.

**Comment by jpaulodit** [comment]
@stevearc Thank you for the suggestion. But I realized it was't going to fix it. When I do pip install in verbose mode, the output clearly shows pip is talking to all the indexes even if it already found the package in the default index.
