### ISSUE TITLE
High CPU usage.

### ISSUE THREAD

**Issue by luqasz** [stevearc/pypicloud#115]
Hi.

Thx for your application. It does make a difference when using it. Our CI servers when building, can put a high load on pypicloud. Simultaneous deploys on ~120 instances fails as pypi is overloaded. Any idea what can be done to increase pypicloud performance ?

What we use:
* redis cache
* 25 CI servers
* s3 storage
* c4.xlarge instance
* fallback set to redirect

Maybe my problem somehow refers to #110

**Comment by luqasz** [comment]
Hi.

I've added some caching in nginx and it reduced CPU load significantly.

In http context:
```
uwsgi_cache_path /tmp levels=1:2 keys_zone=pypi_cache:10m max_size=1g inactive=1h;
```
In server context:
```
    location /pypi {
        uwsgi_cache pypi_cache;
        uwsgi_cache_valid 200 5m;
        # cache 302 responses which correspond to redirects to PyPI for packages not on PyPICloud
        uwsgi_cache_valid 302 1h;
        uwsgi_cache_methods GET;
        # distinguish by request_uri
        uwsgi_cache_key $request_uri;
        uwsgi_pass 127.0.0.1:8080;
        include uwsgi_params;
    }
```

Since we do not host a lot of packages, we often return 302.

**Comment by stevearc** [comment]
It's always hard to find the root cause of slowness without a proper profile, but I had to take a shot in the dark I would say maybe the slow cryptography library. If you haven't already done so, try setting [storage.redirect_urls = true](http://pypicloud.readthedocs.io/en/latest/topics/redirect_urls.html#redirect-detail).

Another idea, if you have set `pypi.always_show_upstream = true` then I could see a path where that could cause a lot of slowdown. If it looks like that might be the problem then I could investigate a way to speed that up with caching.

If you can get any sort of profile I'd be very curious to see what appears to be the bottleneck.

**Comment by luqasz** [comment]
How to gather profile ?

**Comment by stevearc** [comment]
You would use [WSGI profiling middleware](http://werkzeug.pocoo.org/docs/0.12/contrib/profiler/)

If you want I threw together a quick patch here: https://github.com/stevearc/pypicloud/commit/210cf411efad2ad33d57ea3be704e7d09bbedc94
You can grab that and add the following to your config file:
```
profile.enable = true
profile.dir = prof
```
Then it should log pstat files to the `prof` directory. You can analyze them with `python -m pstats` or send them to me and I'll take a look

**Comment by luqasz** [comment]
@fizyk @mmaslowskicc for your information.

**Comment by luqasz** [comment]
@stevearc Thx for this patch. I can't promise you when I will check this.

**Comment by underyx** [comment]
in a 3092ms `/simple/<package-name>/` request I found this in the profiling output:

```
        1    0.000    0.000    2.425    2.425 /usr/local/lib/python2.7/site-pack
ages/passlib/handlers/sha2_crypt.py:369(_calc_checksum_os_crypt)
```

Is there a way to make use a less aggressive/resource-intensive hashing function?

**Comment by stevearc** [comment]
Was that a spike or is it reliably taking that long? According to this, passlib says that it should be tuned for [all hashes to take ~300ms](http://passlib.readthedocs.io/en/stable/narr/hash-tutorial.html#avgsys), and if it's that far off then something is probably going wrong. The only place we're using that in pypicloud is in https://github.com/stevearc/pypicloud/blob/1.0.0/pypicloud/access/base.py#L231 and it's very straightforward

```python
from passlib.apps import custom_app_context as pwd_context
pwd_context.verify(password, stored_pw))
```
If a standalone script running that takes as long then there's something definitely going wrong with passlib.

**Comment by underyx** [comment]
I just ran this in isolation on the same server and it still takes 526ms per verify call on pypy, and 979ms on CPython locally, which adds up to *lots* of time when installing a typical `-r requirements.txt`, since authentication is done for every single request.

What we've done is that we manually edited the database for the most used users to have a password hash with only 1000 hashes which apparently is still fairly secure but takes less than a millisecond to verify with pypy. For reference, by default the rounds are around 600-700k.

Considering that with `pip` users need to be authenticated way more often than a typical site, would it be possible for pypicloud to use 1000 rounds by default? Or at least, making this a config option?

**Comment by stevearc** [comment]
Added a config option (`auth.rounds`) to configure the number of rounds on the password hash in [1.0.2](https://pypi.python.org/pypi/pypicloud/1.0.2)

**Comment by underyx** [comment]
That's freaking awesome @stevearc, thank you!

**Comment by stevearc** [comment]
The CPU issue got reported again in #237 so as of [version 1.0.14](https://pypicloud.readthedocs.io/en/latest/changes.html) the config defaults are for fast pw hashing, and there are more options for tweaking the pw hashing behavior. Assuming this is resolved.
