### ISSUE TITLE
package versions with epochs aren't considered "release"

### ISSUE THREAD

**Issue by triplepoint** [stevearc/pypicloud#121]
The regex check for `is_prerelease()` allows only `X.Y.Z.A.B.C` style versions:
https://github.com/stevearc/pypicloud/blob/master/pypicloud/models.py#L62

The PEP440 spec, however allows for version epochs, to handle the scenario of a project changing from, say, `2014.12.23` style versions to `2.3.4` style versions.
https://www.python.org/dev/peps/pep-0440/#version-epochs

Reading pep 440 closely, it's not explicitly stated that versions with epochs can be considered "final release" versions, but it certainly seems logical.

And now that I go trolling through the pypi.python.org code, it doesn't look like it's supported there either.

Maybe this is part of a larger discussion about PEP 440's ambiguity?

**Comment by stevearc** [comment]
Yeah I don't know if I didn't handle version epochs because I was lazy or because I missed that particular piece of 440. I'm working on a 1.0 branch now that's going to do a bunch of things like migrate to boto3, and along with those changes I'm also getting rid of the "most recent stable/unstable" feature. I think it adds unnecessary complication and barely any benefit. So this problem might just...disappear :)

**Comment by triplepoint** [comment]
I'd still think the distinction affected things like `pip install --pre`?  I have no idea if supporting that pip flag is required as part of a PEP spec, do you?

**Comment by stevearc** [comment]
Oh, all of that logic is inside of pip. It just scans the list of packages that are available and then decides which one to install based on the arguments you passed it. The server doesn't and can't do anything to influence how that works.

**Comment by triplepoint** [comment]
I'm going to close this, since it doesn't really look like there's any need for changes.  It was an interesting discussion, though.
