### ISSUE TITLE
Cache S3 signed URLs

### ISSUE THREAD

**Issue by garrettheel** [stevearc/pypicloud#134]
Hey Steve!

It'd be great if pypicloud had an option to cache presigned S3 URLs in-memory for some duration (shorter than the S3 expiry time, of course). Any thoughts around adding that?

Thanks

**Comment by stevearc** [comment]
Hi Garrett

An earlier (much earlier) version of pypicloud did exactly that, but it was removed because it added a lot of complexity. Besides the additional caching & invalidation, if you're using role credentials and you sign a URL intending to keep it valid for 7 days, but your role credentials expire in an hour, the signed URL will only be valid for an hour. This is kind of a pain to deal with because boto doesn't expose that data (though I'm moving over to boto3 and maybe it's handled better?)

I always recommend using [storage.redirect_urls = true](http://pypicloud.readthedocs.io/en/latest/topics/redirect_urls.html#redirect-detail) if you aren't already; that'll speed things up a lot. Can I ask why you're requesting this feature? Are you running into CPU bottlenecks?
