### ISSUE TITLE
data-requires-python is not present for cached packages

### ISSUE THREAD

**Issue by s-maj** [stevearc/pypicloud#219]
I really like this project and it works well but I am experiencing quite arcane behaviour in one case: 

pypicloud setup:
```
- python:3.6-slim-buster
- pypicloud[dynamo]==1.0.11
- uwsgi==2.0.18
- pastescript==3.1.0
```

Test setup:
```
docker run -it python:2.7-slim-buster /bin/bash
<...>
Digest: sha256:4149310fdae239c7b09aa5fa04263e86b89d11da9bfb1116b4f74782358bfea8
Status: Downloaded newer image for python:2.7-slim-buster
```
With pypycloud:
```
root@2c61a17415d9:/# pip install --no-cache-dir --prefer-binary --index-url https://my-private-pypicloud-repo.com/simple/ nameko==2.11.0
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://my-private-pypicloud-repo.com/simple/
Collecting nameko==2.11.0
  Downloading https://my-private-pypicloud-repo.com/api/package/nameko/nameko-2.11.0-py2.py3-none-any.whl (69kB)
     |████████████████████████████████| 71kB 3.5MB/s
Collecting kombu<5,>=4.2.0 (from nameko==2.11.0)
  Downloading https://my-private-pypicloud-repo.com/api/package/kombu/kombu-4.6.3-py2.py3-none-any.whl (181kB)
     |████████████████████████████████| 184kB 6.4MB/s
Collecting werkzeug>=0.9 (from nameko==2.11.0)
  Downloading https://my-private-pypicloud-repo.com/api/package/werkzeug/Werkzeug-0.15.5-py2.py3-none-any.whl (328kB)
     |████████████████████████████████| 337kB 11.0MB/s
Collecting six>=1.9.0 (from nameko==2.11.0)
  Downloading https://my-private-pypicloud-repo.com/api/package/six/six-1.12.0-py2.py3-none-any.whl
Collecting eventlet>=0.20.1 (from nameko==2.11.0)
  Downloading https://my-private-pypicloud-repo.com/api/package/eventlet/eventlet-0.25.0-py2.py3-none-any.whl (222kB)
     |████████████████████████████████| 225kB 13.6MB/s
Collecting path.py>=6.2 (from nameko==2.11.0)
  Downloading https://my-private-pypicloud-repo.com/api/package/path-py/path.py-12.0-py2.py3-none-any.whl
ERROR: Package 'path.py' requires a different Python: 2.7.16 not in '>=3.5'
```
Directly, from official pypi it works just fine:
```
root@2c61a17415d9:/# pip install --no-cache-dir --prefer-binary nameko==2.11.0
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting nameko==2.11.0
  Downloading https://files.pythonhosted.org/packages/10/e9/218f66b0ff5b2aac02f93cf13574b9c1c6d4ff6dadf24941d29b48f06474/nameko-2.11.0-py2.py3-none-any.whl (69kB)
     |████████████████████████████████| 71kB 1.6MB/s
Collecting kombu<5,>=4.2.0 (from nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/8f/f6/a60d03e6179166134aab2ee15603641eeb91c6ac9344018209d3ef13fb7c/kombu-4.6.3-py2.py3-none-any.whl (181kB)
     |████████████████████████████████| 184kB 4.3MB/s
Collecting werkzeug>=0.9 (from nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/d1/ab/d3bed6b92042622d24decc7aadc8877badf18aeca1571045840ad4956d3f/Werkzeug-0.15.5-py2.py3-none-any.whl (328kB)
     |████████████████████████████████| 337kB 12.3MB/s
Collecting six>=1.9.0 (from nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting eventlet>=0.20.1 (from nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/b7/5a/8b667fcc2e21f988e1a50adc666d4e3e57f3bff7966a41605e60add6229d/eventlet-0.25.0-py2.py3-none-any.whl (222kB)
     |████████████████████████████████| 225kB 15.1MB/s
Collecting path.py>=6.2 (from nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/1e/4a/6e20d9e264d2eb4977b94ee2f189d5c4a4819239ce063027a952014b6670/path.py-11.5.2-py2.py3-none-any.whl
Collecting requests>=1.2.0 (from nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 18.2MB/s
Collecting pyyaml>=3.10 (from nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
     |████████████████████████████████| 266kB 16.5MB/s
Collecting mock>=1.2 (from nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl
Collecting wrapt>=1.0.0 (from nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
Collecting amqp<3.0,>=2.5.0 (from kombu<5,>=4.2.0->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/45/91/877ea2d1c3234dbb32e818d281615232468ff8a4a783a8fc264862b9f77b/amqp-2.5.0-py2.py3-none-any.whl (49kB)
     |████████████████████████████████| 51kB 18.2MB/s
Collecting enum34; python_version < "3.4" (from eventlet>=0.20.1->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting monotonic>=1.4 (from eventlet>=0.20.1->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting dnspython>=1.15.0 (from eventlet>=0.20.1->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl (188kB)
     |████████████████████████████████| 194kB 10.4MB/s
Collecting greenlet>=0.3 (from eventlet>=0.20.1->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/8b/6e/f2d25875713ad0885c8d3c69269697406652e6f64e1a6bd8264f7a609327/greenlet-0.4.15-cp27-cp27mu-manylinux1_x86_64.whl
Collecting importlib-metadata>=0.5 (from path.py>=6.2->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/ad/aa/25fcbded2ab4ed4ff3071d1e000cd4f8f9c65653d2d7157dd105a8e81d42/importlib_metadata-0.19-py2.py3-none-any.whl
Collecting backports.os; python_version == "2.7" and sys_platform == "linux2" (from path.py>=6.2->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/20/c2/193ff30cab747f205535a3a8c24fcc7647dbaf0aa667b7dd580a740b8de4/backports.os-0.1.1-py2-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=1.2.0->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)
     |████████████████████████████████| 153kB 13.0MB/s
Collecting certifi>=2017.4.17 (from requests>=1.2.0->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl (157kB)
     |████████████████████████████████| 163kB 10.2MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>=1.2.0->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
     |████████████████████████████████| 143kB 10.9MB/s
Collecting idna<2.9,>=2.5 (from requests>=1.2.0->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 14.7MB/s
Collecting funcsigs>=1; python_version < "3.3" (from mock>=1.2->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting vine<5.0.0a1,>=1.1.3 (from amqp<3.0,>=2.5.0->kombu<5,>=4.2.0->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=0.5->path.py>=6.2->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/da/bd/1a5fdf15aa44231fd09f63ecf175b60f057ae37ec65b343bb009364923f3/zipp-0.5.2-py2.py3-none-any.whl
Collecting configparser>=3.5; python_version < "3" (from importlib-metadata>=0.5->path.py>=6.2->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/ba/05/6c96328e92e625fc31445d24d75a2c92ef9ba34fc5b037fe69693c362a0d/configparser-3.7.4-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3" (from importlib-metadata>=0.5->path.py>=6.2->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl
Collecting pathlib2; python_version == "3.4.*" or python_version < "3" (from importlib-metadata>=0.5->path.py>=6.2->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/67/c6/4dbf5dfdbe1140cadf765c3896acc098578626c35721bc7d3eb35f6a8fc1/pathlib2-2.3.4-py2.py3-none-any.whl
Collecting future (from backports.os; python_version == "2.7" and sys_platform == "linux2"->path.py>=6.2->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
     |████████████████████████████████| 829kB 10.9MB/s
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "3.4.*" or python_version < "3"->importlib-metadata>=0.5->path.py>=6.2->nameko==2.11.0)
  Downloading https://files.pythonhosted.org/packages/df/f5/9c052db7bd54d0cbf1bc0bb6554362bba1012d03e5888950a4f5c5dadc4e/scandir-1.10.0.tar.gz
Building wheels for collected packages: pyyaml, wrapt, future, scandir
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.1.2-cp27-cp27mu-linux_x86_64.whl size=44911 sha256=5f25ad4bafdbb3f1e2aa4b2f371ad4d89a0b660957a958cd9287bd837296c990
  Stored in directory: /tmp/pip-ephem-wheel-cache-mFXEOr/wheels/d9/45/dd/65f0b38450c47cf7e5312883deb97d065e030c5cca0a365030
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.11.2-cp27-none-any.whl size=19590 sha256=10c63bab6299b715adcf57d9f439e50e8a6648a7cd81cc0e21d3566eda4fdc4c
  Stored in directory: /tmp/pip-ephem-wheel-cache-mFXEOr/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.17.1-cp27-none-any.whl size=500236 sha256=80648070b8a019851b855501fe710458b4b898b1bc9bc7ee81c1441d5b66ece5
  Stored in directory: /tmp/pip-ephem-wheel-cache-mFXEOr/wheels/0c/61/d2/d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
  Building wheel for scandir (setup.py) ... done
  Created wheel for scandir: filename=scandir-1.10.0-cp27-cp27mu-linux_x86_64.whl size=11146 sha256=9fa6731f3e64a4cecd32441d02875abb60b8da28b84b1fbc208e3cf12d9ad67c
  Stored in directory: /tmp/pip-ephem-wheel-cache-mFXEOr/wheels/91/95/75/19c98a91239878abbc7c59970abd3b4e0438a7dd5b61778335
Successfully built pyyaml wrapt future scandir
Installing collected packages: vine, amqp, kombu, werkzeug, six, enum34, monotonic, dnspython, greenlet, eventlet, zipp, configparser, contextlib2, scandir, pathlib2, importlib-metadata, future, backports.os, path.py, urllib3, certifi, chardet, idna, requests, pyyaml, funcsigs, mock, wrapt, nameko
Successfully installed amqp-2.5.0 backports.os-0.1.1 certifi-2019.6.16 chardet-3.0.4 configparser-3.7.4 contextlib2-0.5.5 dnspython-1.16.0 enum34-1.1.6 eventlet-0.25.0 funcsigs-1.0.2 future-0.17.1 greenlet-0.4.15 idna-2.8 importlib-metadata-0.19 kombu-4.6.3 mock-3.0.5 monotonic-1.5 nameko-2.11.0 path.py-11.5.2 pathlib2-2.3.4 pyyaml-5.1.2 requests-2.22.0 scandir-1.10.0 six-1.12.0 urllib3-1.25.3 vine-1.3.0 werkzeug-0.15.5 wrapt-1.11.2 zipp-0.5.2
```

pypicloud config:
```
[app:main]
use = egg:pypicloud

pyramid.reload_templates = false
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en

# Auth
pypi.auth = aws_secrets_manager
auth.region_name = <redacted>
auth.secret_id = <redacted>

pypi.default_write = authenticated
pypi.default_read = authenticated
pypi.cache_update = authenticated

# S3
pypi.storage = s3
storage.region_name = <redacted>
storage.bucket = <redacted>
storage.redirect_urls = true

# DynamoDB
pypi.db = dynamo
db.region_name = <redacted>
db.namespace = <redacted>

pypi.fallback = cache
pypi.always_show_upstream = true

session.encrypt_key = <redacted>
session.validate_key = <redacted>
session.secure = False
session.invalidate_corrupt = true

[uwsgi]
paste = config:%p
paste-logger = %p
master = true
uid = pypicloud
gid = pypicloud
processes = 5
reload-mercy = 15
worker-reload-mercy = 15
enable-threads = true
max-requests = 1000
http = 0.0.0.0:8080

[loggers]
<...>
```

**Comment by s-maj** [comment]
Ok, so it looks like `data-requires-python` ([PEP-0503](https://www.python.org/dev/peps/pep-0503/)) is not preserved when packages are being cached. Eg. 
pypi: `
href="https://files.pythonhosted.org/packages/dc/a8/c123c1b3dfa4678d210df54ef795642300a0a56860668290f544810b7784/path.py-11.5.2.tar.gz#sha256=de7cd643affbc23e56533a6e8d551ecdee4983501a08c24e4e71565202d8cdaa" data-requires-python="&gt;=2.7,!=3.1,!=3.2,!=3.3">path.py-11.5.2.tar.gz
`
where for pypicloud it's just a link to the file.

**Comment by stevearc** [comment]
This appears to be a limitation of [distlib](https://bitbucket.org/pypa/distlib/src/default/), which I'm using to scrape pypi.org. It returns the urls of the packages, but it doesn't seem to provide the `data-requires-python` metadata 😕

**Comment by pbasista** [comment]
> it doesn't seem to provide the data-requires-python metadata :confused:

That might be true, but this metadata is also present in packages themselves, so you can extract it from there. For instance, for wheel packages you can do it like this:

```python
from distlib.wheel import Wheel
wheel = Wheel(filename="setuptools-46.0.0-py3-none-any.whl")
data_requires_python = wheel.metadata._legacy.requires_python
```

Perhaps it can be done by using the `setuptools` or `wheel` modules directly.

The consequence of `data-requires-python` not being populated by a local PyPi server (in general, not necessarily `pypicloud`) is that wrong versions are chosen by `pip`, which leads to complaints, for instance https://github.com/pypa/pip/issues/7586. One of the comments on that issue lists specific steps needed to obtain the `Requires-Python` value from a wheel package's metadata:

https://github.com/pypa/pip/issues/7586#issuecomment-573534655

**Comment by leorochael** [comment]
As more packages release non Py2 compatible versions, this issue becomes more of a problem for people trying to migrate their legacy systems from py2 to py3.

@pbasista, scanning wheels is ok for the wheel packages, but the source packages also need the `data-requires-python` attribute, and it's the source packages that are being wrongly pulled from pypicloud in my case (esp. the source version of setuptools 46 being used to build):

```
  Collecting setuptools
    Downloading https://(...).s3.amazonaws.com/(...)/setuptools/setuptools-46.1.3.zip?AWSAccessKeyId=(...)&Signature=(...)&Expires=(...) (862 kB)
  ERROR: Package 'setuptools' requires a different Python: 2.7.17 not in '>=3.5'
```

This happened as part of installing a package from source that specifies the following in `pyproject.toml`:

```
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```

Which caused `pip` to install the latest version of `setuptools` present in the pypicloud index, using the **source** package, inside the isolated environment for building said package, even though the latest version of setuptools is incompatible with Python 2 and there is already an appropriate version of setuptools in the virtualenv.

That is to say: pinning an older setuptools version doesn't help.

So we really need to add `data-requires-python` to source packages as well.

To scan the python version from source packages, one can use [`pkginfo`](https://pypi.org/project/pkginfo/):

```python
import pkginfo
sdist = pkginfo.SDist('/path/to/setuptools-46.1.3.zip')
data_requires_python = sdist.requires_python
```

Either that or, for a quick solution for avoid py3 packages in py2, we'd need a way not to serve source packages, only wheels, which embed at least the 2 vs 3 limitation in the filename, which is better than nothing.

@stevearc, I'd like to try to contribute a PR, but I'm unfamiliar with pypicloud source. Can you give us a pointer to which parts would need to change to make that happen?

Or, as a workaround, is there a quick way not to serve source packages, only wheels, from pypicloud?

**Comment by leorochael** [comment]
Looking at the codebase I couldn't find a trivial way to fix this.

The `SimpleScrapingLocator` from `distlib` looks exclusively at the URLs found in the `href` of the anchor tags of downloadable versions (and only at the basename of the URL at that) in order to extract information on the located project "downloadables".

The rest of the information in the anchor tag is discarded pretty early and pretty deep in the scraping process, and only `href` and `rel` is preserved for each link and added into a tuple list, so there doesn't seem to be a simple way to monkey-patch or subclass the classes involved to preserve the information.

If we're operating in caching mode, as opposed to redirect mode, it'd be possible to scan this information from the downloaded packages, but that would introduce differences in index behavior between caching and redirection mode, which would break [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by stevearc** [comment]
It sounds like it would be difficult to modify distlib to scrape that information from the upstream repo. I don't have numbers on this, but I suspect that 99% of the time the fallback destination people use for pypicloud is the normal pypi. What we could do is start to use the [JSON API](https://warehouse.readthedocs.io/api-reference/json/) in that case, and fall back to using distlib.

So the steps would be

1. Switch to PyPI json API with fallback to distlib
1. Update the cache/storage schema to store the data-requires-python (probably the package hash too while I'm at it)
1. Update the endpoints to serve the new information
1. Probably also provide a script that will fetch that information and update existing packages in-place in storage

I don't have a lot of free time these days, so I can start on it but it won't get done quickly. If you're interested in doing any of these pieces I can provide some code pointers

**Comment by leorochael** [comment]
Code pointers would be welcome. If not me, someone else could try their hand at it.

**Comment by stevearc** [comment]
**1. Switch to PyPI json API with fallback to distlib**
Locator is constructed here: https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/__init__.py#L42-L44
This step would entail making a new locator that's API compatible for the two methods we call: `get_project` and `locate`. All callsites are below
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/views/simple.py#L138
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/views/api.py#L91
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/views/api.py#L223


**2. Update the cache/storage schema to store the data-requires-python (probably the package hash too while I'm at it)**
  **a. Store the data-requires-python and whatever else in the metadata of storage**
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/storage/files.py#L85
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/storage/gcs.py#L168
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/storage/s3.py#L200
And also read that metadata when fetching from storage
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/storage/gcs.py#L134
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/storage/s3.py#L130
(the files.py implementation gets it for free because it just deserializes the json)
  **b. Update the cache schema to store said metadata**
The base model already has a miscellaneous data dict on it
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/models.py#L31-L32
Probably have to add optional args to this method (or do it with **kwargs)
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/cache/base.py#L77
The DynamoDB model already has that data dict and should work the same as the base Package. Anything added to it should be reflected
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/cache/dynamo.py#L38
Redis looks like it's already saving and loading the data dict as well
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/cache/redis_cache.py#L171
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/cache/redis_cache.py#L89
Lastly, the SQLAlchemy model also seems to have the data dict
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/cache/sql.py#L84

So actually looks like minimal work needs to be done for this step

**3. Update the endpoints to serve the new information**
I'm not sure how this is exposed (or if it is) from the `/simple/` endpoints, but the function is here:
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/views/simple.py#L103-L105
and the template is here:
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/templates/package.jinja2#L7-L8
The JSON version of that endpoint is here:
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/views/simple.py#L115-L116


**4. Update the package uploader to accept the new metadata**
This is the one hit by `python setup.py sdist upload`
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/views/simple.py#L22
And the JSON API version of that is here:
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/views/api.py#L139

**5. Update the package fetcher to fetch the new metadata**
This is the function that's used everywhere to transparently fetch a package from upstream and return it
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/views/api.py#L71


**6. Probably also provide a script that will fetch that information and update existing packages in-place in storage**
This will likely be pretty involved and possibly not worth doing, but the scripts are in the `scripts.py` file and it'll probably be similar to the script that migrates packages from one storage backend to another
https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/scripts.py#L213

**Comment by stevearc** [comment]
To document progress, here are the remaining steps to get full support for this feature:

- [x] Accept the metadata in uploads
- [x] Store the metadata in the cache
- [x] Serve the metadata from the /simple endpoint
- [x] Store the metadata in storage
- [ ] Fetch the metadata from pypi
- [ ] Serve the metadata from the /json endpoint

The first three were added in #234, and I just added the fourth

**Comment by leorochael** [comment]
From the progress report, it looks like all that was needed is done...

Is this issue fixed?

**Comment by stevearc** [comment]
Effectively yes! There's one issue where if you set `pypi.use_json_scraper = false` we revert to the distlib scraper which won't fetch the requires-python attributes. However, I haven't heard any complaints recently about the json scraper, so I'm going to assume that it's working well enough for now.
