### ISSUE TITLE
DOC: How does pypicloud compare to warehouse?

### ISSUE THREAD

**Issue by MartinThoma** [stevearc/pypicloud#235]
This is not an issue / enhancement proposal (well, maybe for the docs), but just a simple question: How does pypicloud comapare to https://github.com/pypa/warehouse?

(Cool project, by the way!)

**Comment by stevearc** [comment]
This is a good idea! I honestly don't know a whole lot about warehouse (other than that it powers the new pypi) because it came out after I built pypicloud, and well after I stopped writing a lot of python. I'll do a review of it and see if I can come up with the key meaningful differences

**Comment by MartinThoma** [comment]
That is already interesting to me! (That pypicloud was there before the modern pypi / warehouse). Thank you :hugs:

**Comment by stevearc** [comment]
So here's a brief summary of some of the alternatives to pypicloud

[**warehouse**](https://warehouse.pypa.io/): The official implementation of pypi.org. It's heavy, since it has to do *everything* that pypi.org needs, and as far as I can tell people aren't usually using this to run their own private repositories. Interestingly, it is also built on top of the [Pyramid](https://docs.pylonsproject.org/projects/pyramid/en/latest/index.html) web framework.
[**s3pypi**](https://github.com/novemberfiveco/s3pypi): Leverages Cloudformation and other AWS tools to host a private repo. [Anecdotally](https://medium.com/jobteaser-dev-team/python-packaging-how-do-we-manage-it-at-jobteaser-2bc8d1e9d206) it is easier to set up and cheaper to run, but less customizable.
[**Gemfury**](https://gemfury.com/): SaaS package hosting solution. Looks pretty much like a black box that does what you want.
[**pypiserver**](https://pypi.org/project/pypiserver/): The project that inspired pypicloud. Very simple and straightforward, but only stores packages on the local filesystem.
[**devpi**](https://devpi.net/): Mature project that does a *lot* more than just store and host your packages. It does index inheritance, Jenkins integration, and staged releases with testing to name a few.

**Comment by MartinThoma** [comment]
Wow, thank you so much!

(I'm closing this now as this answers my question perfectly)
