### ISSUE TITLE
Distinguish between cached packages and uploaded (private) packages

### ISSUE THREAD

**Issue by issackelly** [stevearc/pypicloud#277]
Proposed disposition: Improvement

After reading through the docs for cached packages I have a surprising behavior that I'd like to clarify:

My minimal example has the following settings in server.ini (diffs from `picloud-make-config` with filesystem option):

```
pypi.cache_update = 
    everyone
pypi.fallback = cache
```

Then I run the following test in a clean virtualenv

```
# Test Public (Cached) Pull Through Without Pinning
pip install --retries=0 --no-cache-dir --index-url=http://localhost:6543/simple django || exit "No Public Pull Through without pinning"
pip uninstall --yes django
# Test Public (Cached) Pull Through With Pinning
pip install --retries=0 --no-cache-dir --index-url=http://localhost:6543/simple django==3.0.13 || exit "No Public Pull Through with pinning"
```

With fallback=redirect, it behaves as expected, downloading the newest (3.1.7) version of django, then removing it and downloading an older one.

With fallback=cache, it will not go fetch the older version, since there is an existing cached version. I think that this is because with `always_show_upstream=False` it will treat previously cached packages the same as privately uploaded packages.

The behavior I'd like to see is that private packages are special and never allow upstream caches, in order to prevent [this type](https://www.vdoo.com/blog/python-wheel-jacking-supply-chain-attacks) of attack.

I *think* I can achieve this by setting `pypi.always_show_upstream=True` and having a complete list of private packages in `pypi.disallow_fallback` but it seems preferable to have it be a flag on `models.Package`

My intent for the short term is to make a custom IAccess class and possibly a custom Cache class, but I wanted to write this ticket to descirbe the workarounds I needed to do in order to achieve the behavior necessary for our implementation.

**Comment by stevearc** [comment]
You are correct that setting `pypi.always_show_upstream=True` and having a complete list of private packages in `pypi.disallow_fallback` should do what you want, but I agree that it would be more convenient to have a way to automatically lock down a package name once a package is uploaded to it. Some code pointers you're probably already found, but may be helpful:

* Upload happens here: https://github.com/stevearc/pypicloud/blob/71b2e349a6e0c66d41e7c290880afed4ba7cab37/pypicloud/views/simple.py#L34 (and there's a REST upload endpoint here: https://github.com/stevearc/pypicloud/blob/71b2e349a6e0c66d41e7c290880afed4ba7cab37/pypicloud/views/api.py#L145)
* Then if you create a custom IAccess class (you can probably just inherit the existing one) you can add some query logic inside `allowed_permissions` to remove the `fallback` permission for your packages https://github.com/stevearc/pypicloud/blob/71b2e349a6e0c66d41e7c290880afed4ba7cab37/pypicloud/access/base.py#L175. That'll do it for the redirection fallback, but to remove the ability to fetch and cache from upstream you'll also have to change the call to `can_update_cache` https://github.com/stevearc/pypicloud/blob/71b2e349a6e0c66d41e7c290880afed4ba7cab37/pypicloud/access/base.py#L268. It might be easiest to just modify it to take a package name.

It would be a decent amount of plumbing to get it working on all cache & storage backends, because they'll have to all be modified to store & retrieve that bool. It sounds like you're interested in just adding it for your specific implementation though, so it might not be too bad.

**Comment by issackelly** [comment]
Thanks and thank you for all of the initial and ongoing work that makes the whole thing easyish. You're right that I'm most interested in getting it done for my and moving on, but I'll try to at least write down what I did somewhere useful once it works for our whole org.
