### ISSUE TITLE
Uploading arbitrary files

### ISSUE THREAD

**Issue by zupo** [stevearc/pypicloud#59]
My use case: along with eggs that contain our cross-project code, we need to ship a requirements.txt that lists exact dependencies for these eggs. Currently we handle this use case by uploading requirements.txt directly into S3 and giving it a public-read permission. This approach is sub-optimal due to needing an additional manual step after a release that is different than the main step of upload and egg, and because the versions file is then world-readable.

So I'd like to add an ability to upload arbitrary files into folders containing eggs on pypicloud. I just want to see if there are any comments or blockers before I start implementation ...

**Comment by stevearc** [comment]
I think that serving arbitrary files off of S3 is beyond the scope of what pypicloud should do. You are of course free to fork and do whatever you want, but I probably won't want to merge that functionality back into this repo.

With the caveat that I'm not at all familiar with your code or process, it seems like you could accomplish what you want without making edits to pypicloud. Could you zip up the requirements.txt file in the egg file?

If you do decide that this is absolutely necessary functionality, I would steer you in two directions that may be easier. First: you could make a server that sits next to pypicloud and does what you need. It would be small, fast to write, easy to reason about, and you wouldn't need to worry about how to hook it into any of the existing pypicloud code. Second: instead of uploading arbitrary files, you could add support for setting metadata on uploaded files. Then you could upload your requirements.txt to S3 and set a signed S3 url into the metadata of the appropriate packages. If you're going to edit the pypicloud source, I think that would be a much easier task.

**Comment by zupo** [comment]
I forgot to thank you for taking the time for such a well-thought-out reply, so: thank you!
