### ISSUE TITLE
How to use external uWSGI file with existing uWSGI service

### ISSUE THREAD

**Issue by noilly** [stevearc/pypicloud#80]
I am trying to use pypicloud with an existing uWSGI service. I generated the prod.ini file and then extracted what I believe to be the uWSGI related sections and put them in their own file, like:

```
###
# wsgi server configuration
###

[uwsgi]
paste = config:%p
paste-logger = %p
master = true
processes = 20
reload-mercy = 15
worker-reload-mercy = 15
max-requests = 1000
#enable-threads = truesocket = 127.0.0.1:3031
socket = /var/www/services/%n.socket
virtualenv = /var/www/services/velvetpypi

###
# logging configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
###

[loggers]
keys = root

[handlers]
keys = file

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = file

[handler_file]
class = handlers.RotatingFileHandler
args = ('/var/log/pypicloud.log', 'mode=a', 'maxBytes=1000000', 'backupCount=5')
level = NOTSET
formatter = generic

[formatter_generic]
```

My prod.ini looks like this:

```
[app:main]
use = egg:pypicloud

pyramid.reload_templates = False
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en



pypi.storage = s3
storage.access_key = XXXXXXXX
storage.secret_key = XXXXXXXX
storage.bucket = pypi-velvet-bucket

db.url = sqlite:///%(here)s/db.sqlite

auth.admins =
  XXXXX

user.XXXXXX = XXXXXXXX

# For beaker
session.encrypt_key = XXXXXX
session.validate_key = XXXXXXXX
session.secure = True
```

When I execute `pserve prod.ini` I get this error:
`LookupError: No section 'main' (prefixed by 'server') found in config /var/www/services/prod.ini`

**Comment by stevearc** [comment]
If you want to run pypicloud with a uWSGI service you should generally keep the config file intact and start the server with a `uwsgi` command instead of using `pserve`.

When you say you have an existing uWSGI service, how is it being run? If it's in [Emperor mode](http://uwsgi-docs.readthedocs.org/en/latest/Emperor.html) the easiest way to get it up and running is to drop the config file into the emperor directory (or whatever other backend you're using).

**Comment by noilly** [comment]
@stevearc So pserve does not need to be used at all? That actually makes a whole lot more sense!

Existing uWSGI service is being run by systemd and is in emperor mode.

I don't have a whole lot of experience with virtualenv. Is it necessary to run pypicloud in a virtualenv?

**Comment by stevearc** [comment]
It's not necessary to use a virtualenv, but I highly recommend it. Installing python packages at a system level has screwed me before and it's much easier to start over if anything gets messed up (just `rm -r` the virtualenv and make a new one).

If you're running in emperor mode you should be able to just `pip install pypicloud` (in a virtualenv if you're using one), drop the `prod.ini` file in your emperor directory, and it should start running. If anything goes wrong it should be easy to debug by checking the uwsgi log file.

**Comment by noilly** [comment]
Thank you, I did all that, and everything seems to make sense. However, in my uWSGI log I see the following:

`*** no app loaded. going in full dynamic mode ***`

And I can't tell why. I have never used a Pyramid app before, so I'm sure my lack of knowledge is the cause.

**Comment by stevearc** [comment]
I've never seen uWSGI spit out that error before.

Be sure you're watching both the uwsgi stdout and `/var/log/uwsgi/pypicloud.log`. There might be more info in that second file.

I took this config and did some minimal modifications (filled in the XXX, added a virtualenv) and it seemed to work fine with uwsgi `2.0.12`. Maybe the version you're using behaves differently?

I don't know what else I can do to help. Try putting it in a virtualenv, and google around for anything that shows up in the logs. I doubt it's anything related to pyramid because at the package level all it's going to do is return a WSGI server like any other framework. Maybe it's failing to discover the entry point? In my `pip freeze` I have `pyramid==1.6.1`, `Paste==2.0.3`, and `PasteDeploy==1.5.2` (and a bunch of other stuff but I think this is all that's relevant). Check if your versions are significantly different, and you might try twiddling them if they are. You could also give me a full `pip freeze` and I'll test my setup with the exact package versions that you have.

**Comment by noilly** [comment]
I fixed this issue by adding `plugins = python` to the `uwsgi` section of my ini file. Also, I had to hardcode the `db.url`, otherwise I got the error

`OperationalError: (OperationalError) unable to open database file None None`
